### ISSUE TITLE
[SR-15133] Crash when deallocating a never-resumed DispatchSourceTimer

### ISSUE THREAD

**Issue by mickeyl** [apple/swift-corelibs-libdispatch#604]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15133      |
   |Radar             | rdar://problem/82535083         |
   |Original Reporter | @mickeyl      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

macOS 12 beta, Xcode 13 (13A233).

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | libdispatch    |
   |Labels            | Bug, DispatchSourceTimer        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 61e077b082169a945b058843ee5c3245

  </details>

**Issue Description:**

Please consider the following example program which I have uploaded to

<https://github.com/mickeyl/swift-bugs/tree/main/SR15133>

 

Running it from within Xcode crashes with the following backtrace:

(lldb) bt

-   thread \#3, queue = 'com.apple.root.default-qos.cooperative', stop reason = EXC_BREAKPOINT (code=1, subcode=0x100624d9c)  
    frame \#0: 0x0000000100624d9c libdispatch.dylib\`\_dispatch_queue_xref_dispose.cold.2 + 36  
    frame \#1: 0x00000001005ea2ec libdispatch.dylib\`\_dispatch_queue_xref_dispose + 64  
    frame \#2: 0x00000001005e17f8 libdispatch.dylib\`-\[OS_dispatch_source \_xref_dispose\] + 28  
    frame \#3: 0x00000001000060f8 SR15133\`StreamCommand.deinit(self=0x0000000105105820) at StreamCommandQueue.swift:0  
    frame \#4: 0x0000000100006120 SR15133\`StreamCommand.\_\_deallocating_deinit(self=0x0000000105105820) at StreamCommandQueue.swift:0  
    frame \#5: 0x00000001a2f6b774 libswiftCore.dylib\`\_swift_release_dealloc + 56

-   frame \#6: 0x00000001000081bc SR15133\`StreamCommandQueue.handleErrorCondition(stream=0x0000000100712b90, event=.errorOccurred, self=0x0000000100712e90) at StreamCommandQueue.swift:182:9  
    frame \#7: 0x0000000100009040 SR15133\`closure \#3 in StreamCommandQueue.stream(self=0x0000000100712e90, aStream=0x0000000100712b90, eventCode=.errorOccurred) at StreamCommandQueue.swift:202:44  
    frame \#8: 0x000000010000ac48 SR15133\`partial apply for closure \#3 in StreamCommandQueue.stream(\_:handle🙂 at \<compiler-generated\>:0  
    frame \#9: 0x0000000100005d5c SR15133\`thunk for @escaping @callee_guaranteed @Sendable @async () -\> () at \<compiler-generated\>:0  
    frame \#10: 0x000000010000ad9c SR15133\`thunk for @escaping @callee_guaranteed @Sendable @async () -\> ()partial apply at \<compiler-generated\>:0  
    frame \#11: 0x000000010000bfac SR15133\`thunk for @escaping @callee_guaranteed @Sendable @async () -\> (@out A) at \<compiler-generated\>:0  
    frame \#12: 0x000000010000cc5c SR15133\`partial apply for thunk for @escaping @callee_guaranteed @Sendable @async () -\> (@out A) at \<compiler-generated\>:0  
    (lldb)

I suspect there is a memory management problem when the stored continuation in the \`StreamCommand\` gets deallocated due to \`self.activeCommand = nil\` while the continuation may continue to run in another task.

**Comment by Kyle-Ye** [comment]
I have encountered the bug in my codebase too.

And I can reproduce it stably with your great example code.

After some digging I can create a more simple reproductive code snippet.

```
// main.swift
import Foundation
import Dispatch

class Command {
    let timer: DispatchSourceTimer
    
    init() {
        self.timer = DispatchSource.makeTimerSource()
    }
}

func test() {
    var command: Command? = Command()
    command = nil
}

test()
dispatchMain()
``` 

Checking the `libdispatch` code https://github.com/apple/swift-corelibs-libdispatch/blob/542b7f32311680b11b6fc8fcb2576955460ba7da/src/queue.c#L2879-L2893

The crash reason is that the object is in a inactive state.

It has nothing to do with `timer.cancel`, `timer.setEventHandler` nor `timer.schedule`.

It is because we create the object but dealloc it before calling `timer.resume`.

The solution is always calling activate/resume after you create the DispatchSourceTimer object.

```swift
class X {
    private var timer: DispatchSourceTimer!

    func y() {
        if timer == nil {
            timer = DispatchSource.makeTimerSource(queue: DispatchQueue.global(qos: .userInteractive))
            timer.resume() // Or timer.activate()
        }
    }
}
```

**Comment by Kyle-Ye** [comment]
@mickeyl Did what I said above convince you? I think it's better to mark this issue as closed to better reflect the status here.
