### ISSUE TITLE
`DispatchTimeInterval` is not `Sendable`

### ISSUE THREAD

**Issue by NachoSoto** [apple/swift-corelibs-libdispatch#787]
**Description**
For example:
> Non-sendable type 'DispatchTimeInterval' passed in implicitly asynchronous call to main actor-isolated function cannot cross actor boundary

Is there a reason why `DispatchTimeInterval` shouldn't be marked as `Sendable`? It's an immutable value type.

**Environment**
- Swift compiler version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
- Xcode version: Xcode 14.3 (14E222b)

**Comment by ktoso** [comment]
Tagging @PriyaAvhad who has looked into this
